# Generated by Django 5.2.11 on 2026-03-10 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Test savollari ✅"),
                            ("fill_gaps", "Bo'sh joylarni to'ldiring 📝"),
                            ("matching", "So'zlarni moslashtiring 🔗"),
                            ("word_search", "So'z qidirish 🔍"),
                            ("word_scramble", "Harflarni joylashtiring 🔤"),
                            ("crossword", "Krossvord 📰"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("grammar", "Grammar"), ("vocabulary", "Vocabulary")],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Boshlang'ich"),
                            ("A2", "A2 - Elementar"),
                            ("B1", "B1 - O'rta"),
                            ("B2", "B2 - Yuqori o'rta"),
                        ],
                        default="A1",
                        max_length=10,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Mashq",
                "verbose_name_plural": "Mashqlar",
            },
        ),
        migrations.CreateModel(
            name="GrammarTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("title_uz", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Boshlang'ich"),
                            ("A2", "A2 - Elementar"),
                            ("B1", "B1 - O'rta"),
                            ("B2", "B2 - Yuqori o'rta"),
                        ],
                        default="A1",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("icon", models.CharField(default="📖", max_length=50)),
            ],
            options={
                "verbose_name": "Grammar Mavzusi",
                "verbose_name_plural": "Grammar Mavzulari",
                "ordering": ["level", "order"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("name_uz", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Boshlang'ich"),
                            ("A2", "A2 - Elementar"),
                            ("B1", "B1 - O'rta"),
                            ("B2", "B2 - Yuqori o'rta"),
                        ],
                        default="A1",
                        max_length=10,
                    ),
                ),
                ("icon", models.CharField(default="📚", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Vocabulary Kategoriyasi",
                "verbose_name_plural": "Vocabulary Kategoriyalari",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.CharField(max_length=256)),
                ("options", models.TextField(blank=True, null=True)),
                ("gap_text", models.TextField(blank=True, null=True)),
                ("matching_pairs", models.TextField(blank=True, null=True)),
                ("word_grid", models.TextField(blank=True, null=True)),
                ("hidden_words", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=10)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="edukids.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                (
                    "completed_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("time_spent", models.IntegerField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="edukids.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edukids_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Natija",
                "verbose_name_plural": "Natijalar",
                "ordering": ["-completed_date"],
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="grammar_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercises",
                to="edukids.grammartopic",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="vocabulary_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercises",
                to="edukids.vocabularycategory",
            ),
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(db_index=True, max_length=100)),
                ("uzbek", models.CharField(db_index=True, max_length=100)),
                (
                    "pronunciation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("example_sentence", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Boshlang'ich"),
                            ("A2", "A2 - Elementar"),
                            ("B1", "B1 - O'rta"),
                            ("B2", "B2 - Yuqori o'rta"),
                        ],
                        db_index=True,
                        default="A1",
                        max_length=10,
                    ),
                ),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="edukids.vocabularycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "So'z",
                "verbose_name_plural": "So'zlar",
            },
        ),
        migrations.CreateModel(
            name="UserGrammarProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                (
                    "grammar_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="edukids.grammartopic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grammar Progressi",
                "verbose_name_plural": "Grammar Progresslari",
                "unique_together": {("user", "grammar_topic")},
            },
        ),
        migrations.CreateModel(
            name="UserWordProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learned", models.BooleanField(default=False)),
                ("review_count", models.IntegerField(default=0)),
                ("last_review", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="edukids.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "So'z Progressi",
                "verbose_name_plural": "So'z Progresslari",
                "unique_together": {("user", "word")},
            },
        ),
    ]
