# Generated by Django 5.2.11 on 2026-03-23 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edukids", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🌟", max_length=50)),
                ("color", models.CharField(default="#667eea", max_length=30)),
                ("career_suggestions", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Qiziqish Kategoriyasi",
                "verbose_name_plural": "Qiziqish Kategoriyalari",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="InterestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("single", "Bitta javob"), ("scale", "1-5 shkala")],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("options", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Qiziqish Savoli",
                "verbose_name_plural": "Qiziqish Savollari",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LogicExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("pattern", "Naqsh topish 🔢"),
                            ("sequence", "Ketma-ketlik 📐"),
                            ("analogy", "Analogiya 🔁"),
                            ("spatial", "Fazoviy fikrlash 🗺️"),
                            ("math_logic", "Matematik mantiq ➕"),
                            ("deduction", "Xulosa chiqarish 🔍"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "Oson ⭐"),
                            (2, "O'rta ⭐⭐"),
                            (3, "Qiyin ⭐⭐⭐"),
                        ],
                        default=1,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🧩", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mantiqiy Mashq",
                "verbose_name_plural": "Mantiqiy Mashqlar",
                "ordering": ["difficulty", "exercise_type"],
            },
        ),
        migrations.CreateModel(
            name="InterestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("scores", models.TextField()),
                ("age", models.IntegerField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "top_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="edukids.interestcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Qiziqish Natijasi",
                "verbose_name_plural": "Qiziqish Natijalari",
                "ordering": ["-completed_date"],
            },
        ),
        migrations.CreateModel(
            name="LogicQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.CharField(max_length=256)),
                ("options", models.TextField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True)),
                ("hint", models.TextField(blank=True)),
                ("points", models.IntegerField(default=10)),
                ("order", models.IntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logic_questions",
                        to="edukids.logicexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantiqiy Savol",
                "verbose_name_plural": "Mantiqiy Savollar",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LogicResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                ("time_spent", models.IntegerField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="edukids.logicexercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logic_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantiq Natijasi",
                "verbose_name_plural": "Mantiq Natijalari",
                "ordering": ["-completed_date"],
            },
        ),
    ]
