# Generated by Django 5.2.11 on 2026-02-06 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_subject_alter_question_options_question_subject_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Maktab nomi")),
                (
                    "region",
                    models.CharField(max_length=100, verbose_name="Viloyat/Shahar"),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tuman/Shahar"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Manzil")),
                (
                    "school_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Maktab raqami"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Maktab",
                "verbose_name_plural": "Maktablar",
                "ordering": ["region", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Test nomi")),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("level", models.IntegerField(default=1, verbose_name="Daraja")),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=60, verbose_name="Davomiyligi (daqiqa)"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(default=1, verbose_name="Maksimal urinishlar"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Boshlanish sanasi"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tugash sanasi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="school_tests", to="exams.question"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_tests",
                        to="exams.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maktab testi",
                "verbose_name_plural": "Maktab testlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        default="teacher", max_length=50, verbose_name="Rol"
                    ),
                ),
                (
                    "can_manage_members",
                    models.BooleanField(
                        default=True, verbose_name="A'zolarni boshqarish"
                    ),
                ),
                (
                    "can_create_tests",
                    models.BooleanField(default=True, verbose_name="Test yaratish"),
                ),
                (
                    "can_print_tests",
                    models.BooleanField(
                        default=True, verbose_name="Testlarni chop etish"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managers",
                        to="exams.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_schools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maktab boshqaruvchisi",
                "verbose_name_plural": "Maktab boshqaruvchilari",
                "unique_together": {("school", "user")},
            },
        ),
        migrations.CreateModel(
            name="SchoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Xabar")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="exams.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maktab a'zoligi",
                "verbose_name_plural": "Maktab a'zoliklari",
                "ordering": ["-requested_at"],
                "unique_together": {("school", "user")},
            },
        ),
    ]
