# Generated by Django 5.2.11 on 2026-02-06 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_school_schooltest_schoolmanager_schoolmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Kategoriya nomi"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL slug"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib raqami")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Yangilik kategoriyasi",
                "verbose_name_plural": "Yangilik kategoriyalari",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Sarlavha")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL slug"
                    ),
                ),
                ("content", models.TextField(verbose_name="Matn")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Qisqacha"
                    ),
                ),
                ("image", models.URLField(blank=True, verbose_name="Rasm URL")),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Asosiy yangilik"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Nashr qilingan"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Nashr sanasi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Muallif",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="exams.newscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
